var kodeWilayah = {
    "72":"Sulawesi Tengah",
    "76":"Sulawesi Barat",
    "73":"Sulawesi Selatan",
    "91-D":"Papua Tengah",
    "92-A":"Papua Barat",
    "75":"Gorontalo",
    "14":"Riau",
    "91-C":"Papua Selatan",
    "34":"Daerah Istimewa Yogyakarta",
    "13":"Sumatera Barat",
    "31":"DKI Jakarta",
    "81":"Maluku",
    "17":"Bengkulu",
    "18":"Lampung",
    "91-A":"Papua",
    "21":"Kepulauan Riau",
    "52":"Nusa Tenggara Barat",
    "15":"Jambi",
    "51":"Bali",
    "35":"Jawa Timur",
    "92-B":"Papua Barat Daya",
    "12":"Sumatera Utara",
    "74":"Sulawesi Tenggara",
    "53":"Nusa Tenggara Timur",
    "63":"Kalimantan Selatan",
    "11":"Aceh",
    "62":"Kalimantan Tengah",
    "91-B":"Papua Pegunungan",
    "19":"Kepulauan Bangka Belitung",
    "16":"Sumatera Selatan",
    "36":"Banten",
    "71":"Sulawesi Utara",
    "65":"Kalimantan Utara",
    "64":"Kalimantan Timur",
    "33":"Jawa Tengah",
    "82":"Maluku Utara",
    "61":"Kalimantan Barat",
    "32":"Jawa Barat"
}
